//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLCONSOLEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int IdProducto { get; set; }
        public string Prod_Nombre { get; set; }
        public int IdCategoria { get; set; }
    }
}
